services:
  - type: web
    name: python-backend-bootcamp-1
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask --app wsgi db upgrade
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Render подставит автоматически
      - key: GITHUB_OAUTH_CLIENT_ID
        value: <твоя ID>
      - key: GITHUB_OAUTH_CLIENT_SECRET
        value: <твой SECRET>
