services:
  - type: web
    name: python-backend-bootcamp-1
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn wsgi:app
    autoDeploy: true
