"""Initial full migration

Revision ID: 6a447d7361e3
Revises: 7824ffbf4b06
Create Date: 2025-08-06 21:50:11.049198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a447d7361e3'
down_revision = '7824ffbf4b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_github_id', ['github_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('github_id')

    # ### end Alembic commands ###
